### PR TITLE
Fix forward_port when using net-ssh 2.9.2.

### PR DESCRIPTION
**Pull request by causton81**
I did a bundle update today and got net-ssh 2.9.2 which causes a problem in forward_port. This patch fixes the problem for me, but I just noticed the whitespace is messed up :(

### CODE REVIEW

**Comment by jkeiser** [comment]
Damn!  Let's see when this got introduced so we can do a version check.

**Comment by jkeiser** [comment]
@causton81 can you explain the issue?  Your patch looks fine (though I'd like it if it either used the same `got_remote_host` pattern as `got_remote_port` or that you fix the `got_remote_port` pattern to match yours--either way) but I'm confused as to what started to go wrong.

**Comment by jkeiser** [comment]
@lynchc pointed out that #263 is the actual issue here.

**Comment by causton81** [comment]
Do you still want the variable name changes?

**Comment by jkeiser** [comment]
@causton81 I made them locally and added a bunch of comments I should have had in there in the first place, retesting now :)

**Comment by kramvan1** [comment]
I ran into this with ChefDK 0.3.6, using this patch seems to be working around it successfully.

**Pull request merged**
